using System.ComponentModel.DataAnnotations;

namespace IT_ELECTIVE_PREFINALS_PROJECT.Models;

public class Department { public int Id { get; set; } [Required] public string Name { get; set; } = ""; public string? Description { get; set; } public bool IsActive { get; set; } public ICollection<Employee> Employees { get; set; } = []; public ICollection<Team> Teams { get; set; } = []; }
public class Employee { public int Id { get; set; } public int DepartmentId { get; set; } [Required] public string FirstName { get; set; } = ""; [Required] public string LastName { get; set; } = ""; [Required] public string Email { get; set; } = ""; [Required] public string JobTitle { get; set; } = ""; public string HireDate { get; set; } = ""; public bool IsActive { get; set; } public Department Department { get; set; } = null!; public ICollection<TeamMember> TeamMemberships { get; set; } = []; public ICollection<TicketAssignment> TicketAssignments { get; set; } = []; public ICollection<TicketComment> TicketComments { get; set; } = []; public string FullName => $"{FirstName} {LastName}"; }
public class Team { public int Id { get; set; } public int DepartmentId { get; set; } [Required] public string Name { get; set; } = ""; public string? Description { get; set; } public Department Department { get; set; } = null!; public ICollection<TeamMember> TeamMembers { get; set; } = []; }
public class TeamMember { public int TeamId { get; set; } public int EmployeeId { get; set; } public string JoinedAt { get; set; } = ""; public Team Team { get; set; } = null!; public Employee Employee { get; set; } = null!; }
public class Customer { public int Id { get; set; } [Required] public string CompanyName { get; set; } = ""; [Required] public string ContactName { get; set; } = ""; [Required] public string Email { get; set; } = ""; public string? Phone { get; set; } public string CreatedAt { get; set; } = ""; public bool IsActive { get; set; } public ICollection<Ticket> Tickets { get; set; } = []; }
public class TicketStatus { public int Id { get; set; } [Required] public string Name { get; set; } = ""; public bool IsClosed { get; set; } public ICollection<Ticket> Tickets { get; set; } = []; }
public class TicketPriority { public int Id { get; set; } [Required] public string Name { get; set; } = ""; public int SortOrder { get; set; } public int ResponseHours { get; set; } public ICollection<Ticket> Tickets { get; set; } = []; }
public class TicketCategory { public int Id { get; set; } public int? ParentCategoryId { get; set; } [Required] public string Name { get; set; } = ""; public string? Description { get; set; } public TicketCategory? ParentCategory { get; set; } public ICollection<TicketCategory> Subcategories { get; set; } = []; public ICollection<Ticket> Tickets { get; set; } = []; }
public class Ticket { public int Id { get; set; } public int CustomerId { get; set; } public int CategoryId { get; set; } public int PriorityId { get; set; } public int StatusId { get; set; } [Required] public string Subject { get; set; } = ""; [Required] public string Description { get; set; } = ""; public string CreatedAt { get; set; } = ""; public string UpdatedAt { get; set; } = ""; public string? DueAt { get; set; } public string? ResolvedAt { get; set; } public string? ClosedAt { get; set; } public Customer Customer { get; set; } = null!; public TicketCategory Category { get; set; } = null!; public TicketPriority Priority { get; set; } = null!; public TicketStatus Status { get; set; } = null!; public ICollection<TicketAssignment> Assignments { get; set; } = []; public ICollection<TicketComment> Comments { get; set; } = []; public ICollection<TicketTag> TicketTags { get; set; } = []; public ICollection<TicketAttachment> Attachments { get; set; } = []; }
public class TicketAssignment { public int TicketId { get; set; } public int EmployeeId { get; set; } public string AssignedAt { get; set; } = ""; public string? UnassignedAt { get; set; } public bool IsPrimary { get; set; } public Ticket Ticket { get; set; } = null!; public Employee Employee { get; set; } = null!; }
public class TicketComment { public int Id { get; set; } public int TicketId { get; set; } public int? EmployeeId { get; set; } [Required] public string Comment { get; set; } = ""; public string CreatedAt { get; set; } = ""; public bool IsInternal { get; set; } public Ticket Ticket { get; set; } = null!; public Employee? Employee { get; set; } }
public class Tag { public int Id { get; set; } [Required] public string Name { get; set; } = ""; public ICollection<TicketTag> TicketTags { get; set; } = []; }
public class TicketTag { public int TicketId { get; set; } public int TagId { get; set; } public Ticket Ticket { get; set; } = null!; public Tag Tag { get; set; } = null!; }
public class TicketAttachment { public int Id { get; set; } public int TicketId { get; set; } [Required] public string FileName { get; set; } = ""; [Required] public string ContentType { get; set; } = ""; public int FileSize { get; set; } public string UploadedAt { get; set; } = ""; public Ticket Ticket { get; set; } = null!; }
